import NavBar from './(Components)/NavBar'
import './globals.css'
import './(CSS)/Gallery.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className='global__header'>
          <NavBar />
        </header>
        {children}
        </body>
    </html>
  )
}
